### ISSUE TITLE
Fir stairs orientation bug / oversight

### ISSUE THREAD

**Issue by Petkip** [TraverseTeam/Traverse#11]
issue happend with the sevtech: ages pack, did not check if also happends with only traverse mod. bellow what i posted on the sevtech github: https://github.com/Darkosto/SevTech-Ages/issues/1928

 
## Issue / Bug

Fir stairs when placed upside down with the back to the east-player looking to the east, afther placing the upside down they turn upright and make the bottum of the block above see true. only happens with the east placement the other three upside down orientations are fine. 

upside down corners are in the wrong orientation.

## Expected Behavior

fir stairs behaving like other stairs

## Steps to Reproduce (for bugs)

1.make a platform few blocks above you
2.face east
3,place fir stair upside down

## Context

was creating a rim under a roof one side isnt beatiful!!!

## Logs

* Client/Server Log: https://gist.github.com/Petkip/8572592f745448f91445eef9d066dfb5
* Crash Log: no crash

## Client Information

* Modpack Version: 3.0.6
* Java Version: jre-x64\1.8.0_25  and jre1.8.0_161 x64, tried both versions normaly play 161
* Launcher Used: twitch

* Memory Allocated: 6.144MB

* Server/LAN/Single Player: single player
* Resourcepack Enabled?: nope
* Optifine Installed?: nope

**Comment by ProfessorProspector** [comment]
I've looked into this and I don't understand what's wrong. Can I get a screenshot?

Unless I'm doing the wrong thing, this works fine for me 
![image](https://user-images.githubusercontent.com/6166773/39088257-724d6d36-4563-11e8-8043-1577618df64e.png)
![image](https://user-images.githubusercontent.com/6166773/39088259-7e103f7c-4563-11e8-9b46-ca6d537b0019.png)

**Comment by Petkip** [comment]
it is the rising sun in the background

using fresh install of sevtech ages.

![minecraft 1 12 2 22-4-2018 13_46_04](https://user-images.githubusercontent.com/38477979/39094661-858ee638-4633-11e8-93dd-6ba5e4a652c4.png)
![minecraft 1 12 2 22-4-2018 13_42_23](https://user-images.githubusercontent.com/38477979/39094650-4f6f5484-4633-11e8-86ac-7cb388732b8b.png)

2 stairs are normal and 2 are upside down, the ones upside down create a see true glitch

![minecraft 1 12 2 22-4-2018 13_42_45](https://user-images.githubusercontent.com/38477979/39094651-4f86b02a-4633-11e8-8314-bc0f05faa4a6.png)
![minecraft 1 12 2 22-4-2018 13_43_22](https://user-images.githubusercontent.com/38477979/39094652-4f9d4a10-4633-11e8-9319-0bade3fa2910.png)
![minecraft 1 12 2 22-4-2018 13_41_20](https://user-images.githubusercontent.com/38477979/39094653-4fb42046-4633-11e8-9062-31b9e256a02b.png)
![minecraft 1 12 2 22-4-2018 13_41_28](https://user-images.githubusercontent.com/38477979/39094654-4fca9632-4633-11e8-9292-58c9c70bf45a.png)
![minecraft 1 12 2 22-4-2018 13_42_05](https://user-images.githubusercontent.com/38477979/39094655-4ff4c7cc-4633-11e8-8a7d-c85ff00846ee.png)


if you need more just say.

**Comment by ProfessorProspector** [comment]
That is really weird, it works totally fine for me in my dev environment. 
![image](https://user-images.githubusercontent.com/6166773/39098095-6e41103c-461a-11e8-9208-656f8301664e.png)

I wonder if there's some mod in SevTech causing some sort of weird conflict?

**Comment by TBoshoven** [comment]
I have the same issue in FTB Revelation 1.8 (Traverse 1.12.1-1.3.1-CustomBuild (1.3.1)).
![2018-04-22_14 44 23](https://user-images.githubusercontent.com/1949124/39098653-052fb52c-463c-11e8-9553-14492897645d.png)
I added Vanilla stairs, placed exactly the same, for contrast.

I noticed that it only happens to upside-down stairs with the open side to the west. All other orientations seem completely fine. I did not check corner stairs.

**Comment by TBoshoven** [comment]
I looked at the code and the model file seems to have changed in the meantime, so this may have already been resolved. I noticed the ticket and figured I might respond, but I'm definitely not running the latest version.

**Comment by ProfessorProspector** [comment]
Ah, ok. I tried running SevTech and it took 12 minutes to load + 6 to create a world but it did indeed happen there. Maybe try replacing Traverse with [this version](https://jenkins.modmuss50.me/job/Prospector/job/Traverse/job/Traverse-1.12/50/artifact/build/libs/Traverse-1.12.2-1.5.0-50.jar) which I'm about to release to CurseForge. Make sure to try it on a backup.

**Comment by Petkip** [comment]
I loaded it with your new version and its fixed! Good job on the quick coding :P, so they just have to update your mod in their pack.

thanks anyway

**Comment by ProfessorProspector** [comment]
Honestly I have no idea when it was fixed, it was probably an accident.
