### ISSUE TITLE
1.12.2 Exception Ticking World 

### ISSUE THREAD

**Issue by captcookie** [TraverseTeam/Traverse#13]
https://pastebin.com/K7cBn4ks

**Comment by captcookie** [comment]
I didnt have the latest version, so it may have been fixed. It was 1.5.0.50

**Comment by captcookie** [comment]
https://pastebin.com/pAaTvUAf

I went to the red sands desert and it happened again. Forge 1673 and latest traverse.

**Comment by ProfessorProspector** [comment]
1.5.2 was just released to CurseForge, it will probably take a bit for approval

**Comment by BrisingrAerowing** [comment]
I just came here to report this. Good to hear it's fixed already.
