### ISSUE TITLE
[Suggestion] Adding config options to enable/disable cobblestone rock formations in certain biomes.

### ISSUE THREAD

**Issue by TripleTomTv** [TraverseTeam/Traverse#15]
Traverse has without a doubt many beautiful biomes to look at, but there's one thing that i think ruins the beauty of some biomes. It's the random cobblestone rock formations seen in the Badlands, Rocky Plains/Plateau and Cliffs biomes.
Rocky Plains already lock rocky enough to me without the cobblestone rock formations but do the Cliffs and Badlands biomes really need those too? The Rocky Plateau i can completely understand having the cobblestone rock formations because then it would be just a Plateau biome. Still i always have this biome disabled, so it doesn't bother me that much.

I hope i don't come off as rude. I only wanted to share my suggestion because i really would love to use all of the biomes the mod offers but then i would have at least 4 biomes in my worlds that i don't find particularly good to look at or to build in.

**Comment by ProfessorProspector** [comment]
Sure, I'll add a config.

**Comment by ProfessorProspector** [comment]
This will be added in version 1.5.3, when that will be out I'm not sure

**Comment by TripleTomTv** [comment]
Thanks a lot! Really appreciate it! :D
