### ISSUE TITLE
[Crash] StackOverflowError Crash

### ISSUE THREAD

**Issue by artdude543** [TraverseTeam/Traverse#17]
Hello!

I briefly spoke to Coded about an issue the other day in regards to this crash report.

- Report: https://gist.github.com/artdude543/154b84c2ccf859970c9ff75dffe52c78

As the saplings provided from this mod are listed. (When removing the other mod listing) another crash occurred with the same crash and only listing your saplings. Today another issue was filed with SevTech Ages with another OverFlow error with your doors this time around.

- Our Linked Isssue: https://github.com/Darkosto/SevTech-Ages/issues/2162
- Report: https://pastebin.com/sDHtiDvz

Just wondering what the issue here, as I've had 4 reports now from people with the error and only the blocks listed from this mod appearing in the reports. It could be a coincidence that your stuff is showing here. But as one of the makers for SevTech Ages, I need to find the cause of this issue as losing servers worlds is not ideal and starting again in this pack is not amazing xD

Any help or insight into the issue would be amazing to let the world owners know how to handle this and to possibly revive their world.

Versioning Information:
- Traverse: 1.12.2-1.3.1 & 1.12.2-1.5.2-54
- Forge: 14.23.2.2651 & 14.23.3.2675

_(Two versions as some are from the 3.0.6 version of the pack and the new beta version)_

**Comment by ProfessorProspector** [comment]
This doesn't make any sense to me at all, sounds like someone made a shitty coremod that's modifying something it shouldn't.
