### ISSUE TITLE
Biome ID's in the config

### ISSUE THREAD

**Issue by SextupleTap** [TraverseTeam/Traverse#20]
Biome ID's should be able to be changed/viewed in the config?

In the wiki biome names and ID's should be added as well so that they can be utilized with modpack tweaking mods.

**Comment by SextupleTap** [comment]
I found an alternative method to obtain mod ID's

**Comment by ProfessorProspector** [comment]
Not sure what you mean. Biome IDs are automatically assigned by Forge and that's not something I can control.

**Comment by ProfessorProspector** [comment]
Most of the biome names are just the same as the display names, except for traverse:green_swamp is Lush Swamp and traverse:temperate_rainforest is Coniferous Forest. The rest are just like Autumnal Woods -> traverse:autumnal_woods

**Comment by ProfessorProspector** [comment]
You can also see the biome names in the autocomplete for the /findbiome command
