### ISSUE TITLE
in biome "Arid Highland" spawns Harvestcraft Frost Gardens.

### ISSUE THREAD

**Issue by ilvrak** [TraverseTeam/Traverse#22]
Frost Gardens related to SNOWY and MOUNTAIN biome types
i guess this is because "Arid Highland" is defined as MOUNTAIN type, but it's must be more SANDY type, because there is sand and temperature setting like in desert.

**Comment by TheCodedOne** [comment]
That sounds more like harvestcraft trying to spawn somewhere it shouldn't

**Comment by ilvrak** [comment]
i ask there. thanx
