### ISSUE TITLE
Suggestion : Biome Weight settings

### ISSUE THREAD

**Issue by aurumvorax** [TraverseTeam/Traverse#23]
I am not familiar with the worldgen code for newer versions, but this used to be possible in 1.7.10.  Also, is it possible to disable certain vanilla biomes?  I know this was difficult with old code, is it still unfeasible?  I really HATE extreme hills.

**Comment by ProfessorProspector** [comment]
I'm going to say no on this, but this will be a feature of Traverse 2 when 1.13 rolls around. Sorry!
