### ISSUE TITLE
Saplings are not oredictionary compatible

### ISSUE THREAD

**Issue by angelnc1989** [TraverseTeam/Traverse#26]
A lot of recipes use ore:treeSapling instead of a specific sapling. It would be nice if Traverse saplings would be added to the oredictionary entry for that.

**Comment by ProfessorProspector** [comment]
All Traverse saplings should already have the treeSapling tag

**Comment by ProfessorProspector** [comment]
Ah, ok. I must've missed the others. I'll get that fixed soon.

**Comment by ProfessorProspector** [comment]
Autumnal saplings and leaves ore dict support has been added, and will be in a version released today.
