### ISSUE TITLE
Add compatibility with Biomes O Plenty

### ISSUE THREAD

**Issue by ZXQWAS** [TraverseTeam/Traverse#27]
This mod would have been so much more useful if it worked with BOP. Most other mods generate their biomes in BOP worlds fine, however Traverse doesn't. Please.

**Comment by ProfessorProspector** [comment]
Yeah, I'm aware. To be honest it's not a huge priority as BoP has a lot of similar biomes to Traverse and more. But I'm aware of why it doesn't work, but I need to change a bit to fix it.

**Comment by ProfessorProspector** [comment]
BOP support has been added and will be in a version released today
