### ISSUE TITLE
Traverse Not offering Fast Leaf Rendering in Optifine.

### ISSUE THREAD

**Issue by KaneHart** [TraverseTeam/Traverse#28]
Sadly Traverse seems to be offing fast rendering correctly for just fast leaves. Sadly I reported a few mods back in the day they fixed it but I can't even remember them now. Hoping they can be fixed it did not seem like a big issue for it in the past.

Thanks.

https://i.imgur.com/GFt1JOh.png

**Comment by ProfessorProspector** [comment]
Would you mind trying without optifine installed to see if it works then?

**Comment by ProfessorProspector** [comment]
This should be fixed in the latest version
