### ISSUE TITLE
Massive Lag Spikes

### ISSUE THREAD

**Issue by jredfox** [TraverseTeam/Traverse#29]
Stay in a world with loaded chunks and there is massive block breaking lag with 2g ram applied.

mc was running at half memory according to f5 yet there was still massive lags making the game unplayable. I took your mod out of my modpack and it worked just fine.

Log:
https://pastebin.com/nRSq1Ryj

ModList:
https://pastebin.com/hVuaBJ2a

**Comment by TheCodedOne** [comment]
Can you provide profiling, list of mods, any kind of actual details rather than assumptions.

**Comment by ProfessorProspector** [comment]
Again, mod list

**Comment by jredfox** [comment]
if I take traverse out there is no lag spikes

**Comment by TheCodedOne** [comment]
Please provide the requested information or this issue will just be closed cause you dont want to supply the needed info. its as simple as that redfox i know your history with complaining about everything and im not gonna have it in my github.

**Comment by liach** [comment]
@jredfox Without a mod list, developers can never reproduce the issue you described. If you supply at least the mod list, developers might be able to reproduce the issue and then investigate it.

**Comment by Moobien** [comment]
I have been using Traverse on a server for months now with no issues

**Comment by jredfox** [comment]
sorry I thought logs contained modlist

**Comment by ProfessorProspector** [comment]
Crash logs do, but it's also good to just provide one even if it is a crash log.

**Comment by modmuss50** [comment]
Can you reproduce the issue with just traverse installed? I see you have a lot of mods that add world gen. If the issue goes away when traverse is installed add the mods back one by one to see if it is an issue that is only caused by another mod.

If you can profile it as well (using a mod like sampler) then that would make it a lot easier to figure out what the issue is. The log you posted does say that BiomesYouGo is causing cascading world gen, so I would start there.

**Comment by jredfox** [comment]
I can say that I can reproduce with just adding the mod and removing it fixes it. It's not my job to fully beta test the issue here with such little mods that do this especially since I don't know all the biomes and how they interact with x mods.

**Comment by modmuss50** [comment]
Traverse isnt in beta, and its not possible for any of us to know what the issue is as your the first person out of many people to have an issue with the performance of the mod. Its not possible to wave a magic wand to fix something we dont know exists.
