### ISSUE TITLE
Error: #item in traverse:models/block/itemblock with Traverse 1.6.0

### ISSUE THREAD

**Issue by realTIMematrix** [TraverseTeam/Traverse#30]
Hi,
i get a warning and error message when using only Traverse with the latest Forge Version 14.23.5.2768 for Minecraft 1.12.2

23:40:42 | net.minecraft.client.renderer.block.model.ModelBlock | main | warn | Unable to resolve texture due to upward reference: #item in traverse:models/block/itemblock
-- | -- | -- | -- | --
23:40:45 | FML | main | error | MultiModel minecraft:builtin/missing is empty (no base model or parts were provided/resolved)
23:40:45 | FML | main | error | MultiModel minecraft:builtin/missing is empty (no base model or parts were provided/resolved)

23:40:42 | net.minecraft.client.renderer.block.model.ModelBlock | main | warn | Unable to resolve texture due to upward reference: #item in traverse:models/block/itemblock
-- | -- | -- | -- | --
23:40:42 | FML | main | info | Max texture size: 16384
23:40:45 | net.minecraft.client.renderer.texture.TextureMap | main | info | Created: 512x512 textures-atlas
23:40:45 | FML | main | error | MultiModel minecraft:builtin/missing is empty (no base model or parts were provided/resolved)
23:40:45 | FML | main | error | MultiModel minecraft:builtin/missing is empty (no base model or parts were provided/resolved)

minecraft@1.12.2,traverse@1.6.0,FML@8.0.99.99,forge@14.23.5.2768,mcp@9.42

**Comment by ProfessorProspector** [comment]
Not a problem; just a forge feature that vanilla doesn't support. The log message is unfortunate
